name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: "henriquebrnetto"
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: henriquebrnetto/greenthumb-api-ci:${{ github.sha }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_TEST }}
        username: "ubuntu"
        key: ${{ secrets.KEY_TEST }}
        port: 22
        script: |
          docker stop greenthumb-api || true
          docker rm --force greenthumb-api || true
          docker run -d \
            -p 8080:8080 \
            --name greenthumb-api \
            --network=rede \
            -e SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
            -e SUPABASE_SECRET="${{ secrets.SUPABASE_SECRET }}" \
            -e SALT="${{ secrets.SALT }}" \
            henriquebrnetto/greenthumb-api-ci:${{ github.sha }}